import sqlite3

baza=sqlite3.connect(":memory:")
c=baza.execute()

c.execute("CREATE TABLE pytania(id integer primary key,trescPytania varchar(100))")
c.execute("INSERT INTO pytanie(trescPytania) VALUES('Płeć')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Jak oceniasz swój sposób odżywiania?')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Jak często uprawiasz sport?')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Czy prowadzisz stresujący tryb życia')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Czy palisz papierosy nałogowo?')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Czy pijesz alkohol?')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Czy korzystasz z innych używek?')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Czy masz problemy z układem krążeniowym')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Czy w Twojej rodzinie ma ktoś problemy z układem krążeniowym')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Czy przeszedłeś chorobę nowotworową?')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Czy ktoś z rodziny przeszedł chorobę nowotworową?')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Czy w rodzinie bywały przypadki zachorowań na Alzheimera?')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Czy doznałeś kiedyś urazu głowy?')")
c.execute("INSERT INTO pytania(trescPytania) VALUES('Wykształcenie')")

c.execute("CREATE TABLE odpowiedzi(id integer primary key, trescOdpowiedzi varchar(30) )")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Kobieta')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Mężczyzna')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Bardzo dobrze')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Poprawnie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Mogłoby być lepiej')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Źle')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Codziennie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('3-5 razy w tygodniu')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('2-3 razy w tygodniu')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Sporadycznie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Nigdy, nie mam czasu na trening')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Zdecydowanie tak')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Raczej tak')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Raczej nie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Zdecydowanie nie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Tak')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Nie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Zdecydowanie nie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Piję tylko w wyjątkowych sytuacjach')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Piję zawsze kiedy mam okazję')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Piję nałogowo')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Tak')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Nie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Tak')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Nie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Tak')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Nie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Tak')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Nie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Tak')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Nie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Tak')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Nie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Tak')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('Nie')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('podstawowe nieukończone i bez wykształcenia')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('podstawowe ukończone')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('zasadnicze zawodowe')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('średnie zawodowe')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('średnie ogólnokształcące')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('policealne')")
c.execute("INSERT INTO odpowiedzi(trescOdpowiedzi) VALUES('wyższe')")

c.execute("CREATE TABLE relacja_pytanie_odpowiedz(id integer primary key,)")